# Project information
site_name: Mod By Daylight Docs
site_description: Dead by Daylight Modding Documentation
site_url: https://modbydaylight.com/

# Repository
# repo_name: ModByDaylight/Documentation
repo_url: https://github.com/ModByDaylight/Documentation
extra:
  embed_image: /img/logo.png

theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  palette:
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  icon:
    logo: logo
    repo: fontawesome/brands/github

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ModByDaylight
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xkbgW3aCRJ

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
nav:
- Home: index.md
- Development:
  - Development: Development/index.md
  - Resources: Development/Resources.md
  - Unreal Engine:
    - Unreal Engine: Development/UnrealEngine/index.md
    - Project Setup: Development/UnrealEngine/ProjectSetup.md
    - Chunking: Development/UnrealEngine/Chunking.md
  - Modding Guides:
    - Textures: Development/ModdingGuides/Textures.md
    - Sounds: Development/ModdingGuides/Sounds.md
    - Emission Maps: Development/ModdingGuides/EmissionMaps.md
    - Material Instances: Development/ModdingGuides/MaterialInstances.md
    - Meshes:
      - Meshes: Development/ModdingGuides/Meshes/index.md
      - Static Meshes: Development/ModdingGuides/Meshes/StaticMesh.md
      - Skeletal Meshes: Development/ModdingGuides/Meshes/SkeletalMesh.md
    - Physics: Development/ModdingGuides/Physics.md
    - Animations: Development/ModdingGuides/Animations.md
    - Advanced:
      - Custom Cosmetics: Development/ModdingGuides/Advanced/CustomCosmetics.md
      - Custom Items: Development/ModdingGuides/Advanced/CustomItems.md
      - Custom Maps: Development/ModdingGuides/Advanced/CustomMaps.md
- Private Server:
  - Private Server: PrivateServer/index.md
  - Mod Installation: PrivateServer/ModInstallation.md
  - Config Edits: PrivateServer/ConfigEdits.md
- Dev Build:
  - Dev Build: DevBuild/index.md
  - Server:
    - Server: DevBuild/Server/index.md
    - Setup: DevBuild/Server/Setup.md
    - Config: DevBuild/Server/Config.md
    - Commands: DevBuild/Server/Commands.md
  - Fiddler Setup: DevBuild/FiddlerSetup.md
  - Cinematics: DevBuild/Cinematics.md
  - Console Usage: DevBuild/ConsoleUsage.md
  - Advanced Console Usage: DevBuild/AdvancedConsoleUsage.md
  - Useful Commands: DevBuild/UsefulCommands.md
  - Character IDs: DevBuild/CharacterIds.md