site_name: Mod By Daylight Docs
site_description: Dead by Daylight Modding Documentation
embed_image: /img/logo.png
site_url: https://modbydaylight.com/
repo_url: https://github.com/ModByDaylight/Documentation

theme:
  name: mkdocs
  custom_dir: theme_override/
extra_css:
  - 'style.css'
extra_javascript:
  - '/scripts/popper.min.js'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
nav:
  - '3pl': '3pl.md'
  - Home: index.md
  - Private Server:
    - Private Server: PrivateServer/index.md
    - Mod Installation: PrivateServer/ModInstallation.md
  - Dev Build:
    - Dev Build: DevBuild/index.md
    - Server:
      - Server: DevBuild/Server/index.md
      - Setup: DevBuild/Server/Setup.md
      - Config: DevBuild/Server/Config.md
      - Commands: DevBuild/Server/Commands.md
    - Fiddler Setup: DevBuild/FiddlerSetup.md
