name: PR Preview

on:
  pull_request:
    branches:
      - dev
    types:
      - labeled

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to preview')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: npm run setup

      - name: Build
        run: npm run build

  push:
    name: Push
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to preview')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/modbydaylight/documentation-clone:pr${{ github.event.number }}

      - name: Update Docker image
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL_PR }}${{ github.event.number }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}